apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-backend
  namespace: gitops-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitops-backend
  template:
    metadata:
      labels:
        app: gitops-backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/isaacam50/gitops-backend:holaaa-20260202-052423
          ports:
            - containerPort: 8000
          env:
            # Variables normales
            - name: USERNAME
              value: "isaac"
            - name: ENVIRONMENT
              value: "production"
            - name: LOG_LEVEL
              value: "INFO"
            - name: PORT
              value: "8000"
            - name: HOST
              value: "0.0.0.0"
            - name: GITHUB_USERNAME
              value: "IsaacAM50"
            - name: REPO_NAME
              value: "GitOps"
            - name: GITOPS_REPO_NAME
              value: "GitOps-Manifests"
            # Secrets (referencias)
            - name: CIRCLECI_TOKEN
              valueFrom:
                secretKeyRef:
                  name: tokens-secrets
                  key: circleci-token
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: tokens-secrets
                  key: github-token
            # ConfigMap values
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: app-name
            - name: DEPLOYED_AT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: deployed-at
