---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tokens-secrets
  namespace: gitops-app
spec:
  encryptedData:
    circleci-token: AgBVx3G3mCi0GnnfccNTZ7IiTaYVK4RPU0ODEWYoLKcgx0oVfGsW/Tzs6uYBGGnFgpwbyZJtx66aSYLs6irIa1dwlLmdUULkqupINr65+hHA2U4LdDaX+aHhniYy8bU9RrykaWUGBAO3yX1XpsoOGW0AxrfSanqla88suy72uXAaHCIigi7fS22pqM71aM9NXi5QgnNcIkSEkB7U2XrCO23myyvVS0t0Y0oufScHBnl4D7HAlPHufcuENzjQuzHydBkJEBVfS/GEqRwWLfKtDhnU3/CiHurTAhcPzUbv+Fw7z/ySL23EPnaZZ4VMlY8V75oJHz588Se6ZD6r6xFdH9dUg30BSw+OMYo2df6kcCBFKKfwgeAFvdJ+cIf0ZmxlGAlY2YkIiwJg4lsjVlCnt/GVg67WtttUqiG2RDmeDG93PnUMgxusjwIvu6Ca3Ytq50lTg09O8ZOZbH/wyeZ+Oth1P58WqHxikgezQSfbYS368yABrg6VSwu2X3qJn4mnN+hpIaNcNJxD4YddmcAKmB1yz3ujGtHzvNwaFDCvVBqAiIb3s4SdN6Z+bLInjLdJUmSP7WpH+npBHmenO9NnMARqoufO40qR4qsoIqx0vqzzvPhbOKUjt0hxUIyYD4pDzZ5K4iTAyT6KMONgbcDntawlraeAyq13/KC+dAGwrSLWB0fzAfCYNqUuv2r38vxzQZTtAk3G/kFglzahRclH1BtZGpD+3mSH3stC+x6esh/EOpKU1T67DIFk7HyN7Kc6eR14/7ze+OAOUOaVFEGdsz4R398puxHf
    github-token: AgBn80zM78bwl39O7QeyHQ6Yzu2PaE8KfgaFheHoC0uzWcof44mBJWoUeY3TM7Wp2YoeqihJmeMKGZ3ktK+t7kaSvfFZXTdd0POlBgxHw2x69+os1cygJNWFW9A9JsGCOdLKqUUTKQB5U4w0G9S7yv9Dz9fdPssWs7KdTsld65CW/ABxWbYwcb0nvAPn3oNIrQqAaDZ96jrYuFH3WR5JS+V36RYJbYBuKQQeQQxmSZ9iDsTLDNBmC8CCUG09SKl0d+Uvh8VXBP8w3pC4yB0CiNBipN7Fa9tKI8Tkb1hFz7RkoGOyyseRLZ1o0TShcjKBYGKeXI+ZHek/uuYRgeXXiOxknEUc+ZOz/xdOcGIxD5j4vUuiAWBotZScwN+IHZ4gJXwXSqW3YnXrEcjUALxnpcPlku3rWWa0nP816KjHyPg3x1rRe/KUvDiB0tFS+Kl+vvdfVNq8SRELEeercqBP3t920uNT94PeRHSY6O/lT4F10wwOxn33uQYBivatQMLZ6lGAnGr3TMIicA85Sc5onLGwFgf3pQljCDGRbvyr4MgXKMft3gPJ3PSDJndzgOH8yYPmwKiEup0ilQowGozt4XpVHUuHoPPd9GAuQpmY8HkL06ED7Yh7nJTFJsJ2npTd6aMsvmxjMEYEZ1lk3yMn11XvpyCiaXXf5fSrJcy2KxZTnUOLiUvx+ghdbte0C8ECBEky7DcAW7eBz6WpA53BjSIx3h4wljs3QYsCfIHx/G1tZsmU+MXUWQt6
  template:
    metadata:
      name: tokens-secrets
      namespace: gitops-app
    type: Opaque
