---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tokens-secrets
  namespace: gitops-app
spec:
  encryptedData:
    circleci-token: AgB/o89pifpRAqK4rvldEOfkJh6dd665MgKeX+CP2ByRFVKLpooiPRHEEziEV9qjR56Ls7vd2tMMv9EtZq3zcHq8JN4ArnTZ/ZNx8Q1tEPYjqZdLJT6HNURdHZETw8Hzo+fiMSYENY7N8PqQEdRmZh8XLAtLt0GUYDFzzkQkfiZ9+EHFAUJVt+QTuPIuVXD2wICdaAf6MA87LOW0IjUsQFSt19iqoBLqH8gQtzVhY487rPk/mqufS1mq+uzkyCFF0lg2yF3Sr1ZF8BtK2CYOrtFExChbdxHDweoX9xXntfZaYGXDHOuX/JiRVcimXtwIBVPvpbUfb0Jkg5ya9ADHdJ4wEb44iUWvbSXhwQw9/3UuHV2ps4YAMbI3UnvmE2LQddfPujSign3MXYPPf7FVN9piq/hICihNs3i8qp0xV1UN2B7Amap7fSnaV7f5WYpGyD+3XUXVH9CgWJ/RZjhxUpXDbmECv6LOu415dnJl3XgCCP4QUSYKZrSMEt3loBSJ7qu6VPyUgXnYLUVwDjvGbQPlp8En8NzqEO27/dZm8w05N5w8e0XiOxxxCw1O5AVQ56A8WvRktIzT0WS3fwvtd5mOSll55IfpU/zyAfseur7ZDwrR0nmYg39kCbeMespc1dHj3eS29PfhaInrgh5WsksGGErvkhXWTMQbdqpPyYVn/yhLaLX6qGWTKX5NFvtwrZ/ntn1OgwEVu7KHpHwOtQ4k5ngQ4dA180ugLRXyBzS+0Ng+lDLjOkQeyxG2bwVsVDXsCVwqaSiODYwhfbBMixgwTbXQX/vl
    github-token: AgApM1Dp0PkQgt+/bC2zEo416F+urJLvKQQZICZE/Exb7ryrakBnq/Ccjkqj/c1M/kqIFpvcL4qTpztzbUf17VSBywhM8+Yapyy0IJONS0FP+xd1lTRr/bR71c4jyvFuAGQLwQhLnz199zRb2ew978qW7oJSD1HmCa4nLgmAUyEr9PqPyL6gR5JDrtY+Fu2tTK1Bgk2GpXVl8kwfXEuwVGNLDxgqZ5SP3yWUzroIqiq0iiFCUIjVx8wuTvr3H1JbSsRGotNmDP+dUZhzVKk1BjWiBNGbJqMjSh3PKjg2KTnXl0xMGg+ZhKE88M34ExP0I98Y6BetGqR1D4oCjwFENXgkTCfU54gzp67gx5JDYqDoqLIlEyhzmATd3kT22n8mF+qA1ShNeU/WX6jZO+E3ZftnieSS1C7h7OEX7Ma4UxfoBIfcp31U9+SGOEE5BMdn8mxQNsEAQ/ps7/HhoFYBfiMLoFjRCOveDdo450m/YYxmqTwhsyVYirJksTAltzBy/bKU8ArNF5BW5Y4g4NCdy1IbIafVgqpQUHcVUjF86Loyn9k/ByigOERyhWfTRttd9B73EskJyThWzaKR6vTDl4AkU4I7cGtZDQY41InzDRuEqe3UlKLe9u5FeKPn4yKzLyo9JVf+0SmI4DnaADeoFmMBtRa+ErPa3eTa6Zm3xAJfNTTRljGZtUO00Vu2yaEGaQkhY7sOSbTbgUOHw8se7WgT6TlKN4IhqEKY8D8RTXUrjWVnyqUau9r8
  template:
    metadata:
      name: tokens-secrets
      namespace: gitops-app
    type: Opaque
