---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tokens-secrets
  namespace: gitops-app
spec:
  encryptedData:
    circleci-token: AgAHG6UZ7iqGzy2zdWHpgZbBMXBkBiLo5UxsbRrpLXwecWuDXdI0BkGjnR33412CiKjFzPNqSkbeTvPwXEvHshXF5BdIwL2vhp3DQ4zmLMzl69lB0gVaoeL3nwEioaiwF0iM2Tk5CeijABD4i2Hki883Ox/B5V/nNN41VRDjzovEdExn2/6Rgpq+s9C4gQrPkqJb8eiIMXmLvfYMhi5vCfo8Ts3+GoMQmxOe0iFhqMVOUUJgS2E1saZ3BVz1XqD67gY0I2E5fYG/6ZX36F244OEAO1v7+0URXThEXLoeu8QjPz062D2zgpf84GdeYLatsLvePqFf1thwBlrsK9DwltQrLpMMXp0WHd+UE56WhlSB801gxuX+qgPYpiZkB5SGA2gGZefDEBBTNbLiZ4/rqvKLC50L/mP2nss/U4G3e5knpuz4zNNEZJ6VrkMjeOnYqnMSLpC3/PcG/wKXyzB7v2GGfmhOPNk6VcKtJv7WaOxoU4YbELOWm/1XRXEHS10fsnn4gdMt0DPREjwTKSlvRhc8L7dqDbUHM7V2VWiU5UPaVJwbDzbQrxZJcJzzwpYPjR8doQJUzW6QECoh7Oldz6evLKAIsbCCumub3FIjZJlNWnEZamQME7b+qw6mEHYNuztPQNNmk5EVGCeZDUvlmTRymgz19IvvYAi9ppxbITRn/lp/3fnw57Qd+L+cWV9oUf7AxGtjClGHHrKRdbhvR+B+XAmoEFdYvjHRu5SJz/xJW7Q9i6GAHWmcTcS8R9BNqkzoX/pQVP+8OczusPAnB0j6OJ2Or8D+a1hL3g==
    github-token: AgBKEG/c2VsF94SXF31hr3+GEH4W+nHnZTp7bZKwmXA3Ph+zl7SbI0YuaUw0spaGUxt+ROxkReLsnHhffbOwUTOAmmU+cjlGYOtEvPavz7xJQuVyQTbe+BBo12XNLyS/yEQP+5HdrOxFfnSIEtMr2jZbwyaD50fKDoX897bE90NJrrxULtUYhkMPZ36vVbo8sanSxpHwqVCMX1T68M0QeJIILL8sUoiGP21gkFgUXg4WmALWZMOQ72KNhGA3vKqhACZuAu2JnefNJHhb4VcK7e3LaRaH9V79cMzcD9IhsBKq/qOoZ3YDwW3CP7Al2fMZCxHt40iO1hAeUZPO6vUKLvud7rEhcRAhBHjgYRIqyKFNGUO9104fYTDNNypapqezwOuxPhH9ubNK0FxMSd7Wm9ZQJibrNIHmMRFKEosBG2PsRlKvw9uVtaUDkoe1sPmTPDB4aEr98CuqLKNCTdtdnuJac4fncKb3VP+tBoW+LS6q8SMuNEkSct1GdWyr7duSrb8dauVOwvzHWcycjrYjrjmfIHJ6ymFyUV3ngqlgqnaxSuGiKABhgax41L1eD7yEZPduKmiQ3b81+UKNX1APDxnkW/oAx+2nj5GwyMy1yHqUmaMRvlzCzhuX/u9FCvZT9A1AxbbLXqLtUd09KNfe7K0m5palMq+W6O8rq1cZTMIx8gq7Lvif2XDwNfjjZpss83/hy1aSNBdNKe6D91IagDHnl1ILGHgkSkPtD7RA6puLRVflPfLwncSIGr8h+w==
  template:
    metadata:
      name: tokens-secrets
      namespace: gitops-app
    type: Opaque
