---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-secrets
  namespace: gitops-app
spec:
  encryptedData:
    circleci-token: AgCRZ0ISaRr7Md1LBO/z3Pb9qj2x68SnucOPfd8n2zf/xAfit5VyHF/t3d/kkct/IjU8T5+Cw7UeZDG2/2tivnH5AQdDpTz7EQ9E545pSlMOrGjvnl4AiY03LIcpmxtc2unez7aA1EdroYJozPsHKsWdsDPlU1OiP/MFUEvdDXSmEj7pwrK73hveVhSqV1kM44cD2hoXTWn1j9DkaRZDqX+1Hni0T/OsaLrC60jfNm9QmPNr3Vnoa+iZ/M48l6aSARlIty5C/xuU13SMx1z+Yzf83rKFuq7fNlyJz43f2oyptdMsiTqfEx2P7FIkEPA1Nk+5o+4RiM9+qrEp273iArfYzdb1rT7pyAVeEOvImNktz09BtBY0bUb51BQ69NORhqV2V3pr1sDEU2idyKeKOyUGNE68rRcrq+liaY/UcQKz0M1a6mpacjuLO2nY/gd1p+tqMYYCyfJbIR5/IIbzm3CH2bc3iJUxbYjmf4CyRwsvT7q9qvhjMb3fiBVKsrrzCwspUlPTyFWTrP7XSyUm2B2N3ve2CJItOrvSz3daDlArqwJ9rWXANDRs7UNJj/vFBWGVCoaGor+ykweQLxLGofugkATMy7hLkNxpNYVeD+H3NcIothi1BZRr1eOKKMlIwAml8wx6xb6Vzq1//60px78JI+D3uuq2P97tvHwojiU+HkQF0v8B0IoJSD4SKTTlJl7P+SmZplx6A87TPlCVm1O+Aru2S7nV0A5woH8lFdoLFb0+mJs1xjjNkWG3tJYrht5qNEQ9w3ZTzCEZXdIljs696hK8k7zK
    github-token: AgAt37i8cmrsvwEH9587VkgbEblmefS5caklmuahE4Y+pFXWZjFIk3P1V/I1qCqwnWrX5lWY0gOuyn+qy2HGGMzUwQ2Y/R105/E/WezFl/jJO806AFs6Szcn/xuVdNjTL6Iy9IgK8wYNsid7T6syN2MGeWYHc/gFbta/Hz2i4gG7u+GP8mCqKhirVWAQ6UrnB7kgGwcpxLTtSMBjNktKU0CehGH9ZpdhYbFnrhrtuVJkbxyS1A+EHkNeDOWAYvpXHeEfRtwyhxDGwiqo2ImhJxfcKu2WUbsyDwm3xGZOZEf6jlrmHDTx7sDeqjwwd3EvmIay8SAp0yuE0gPMR2ecKe6CzT0aYMquQve+j0ouoEYUnuq21GuxT3ThY0/jtqldWts/1YfpDIr8VHz/HXY0GV/HRHBE5BOeG70c7b3Ya1hWoJAcYb03RhNLpqax1cfm+zqsev1S575d/yzjU0w0yU9OteIHh2UGd3GbMc9mRkdHfBeLURQbjT6P322X7ryD/GzRMzI2m5rGICK+FB44J3Q5QFj3w+IBV/KR00R87D+YtAgFtvpvdY4MrZdLz5pau4HEc02fUAHEcn9dNAlk5MEOstpVImK1LbArJAJJ/PVzcyH1TXU/xm/xpch7BFkJEyrjuYc+HrMDxbJe/2U89TozcaUhE9B7UkEFSpb1k7VLlaLK6uhc3eHo3vJp21jmeAPHKTCRjU0rqEqSH0waAcdUhjLOcTUjgKDxVCKdd0NmBJKQRp3AZNQ9
  template:
    metadata:
      name: app-secrets
      namespace: gitops-app
    type: Opaque
