---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tokens-secrets
  namespace: gitops-app
spec:
  encryptedData:
    circleci-token: AgCaXphP32J0uMV4ErFn9zpCr8v2ZeOPMwGfJwUjhdRsMiGC6K7x+iXxMy6vtsgCvnAK7F3gYClOIeOl90GqWGq20ESioTM5R0h4LPGbkZxAaFvUMycz1kM4j6a8mVMYcm3EQ3QnW//b8Zy1jzLG9955B0ZZYwbsjIW54aWeNtPPyYu4FIPWXEMQp7HbWw1Zgl2VtdK00/hKc1gZqx1MPGn4IjRwAYBalKqlQS+4NW+YIqiFLC0akQxTBIrafROAgEsx7If+JSvehgs5dNxaydKHRD0GYF+xMvklIz1WrOrOO37QH/b0oMem+IWZg5ht4vgiylpgxSTUd7yArAN3P9/v+ImqjsYY13yj6L+RKR3MOLoZ/ZMfYB2K0dGmMMQNFcASx6eCmFoHMeUgz2FxZVvo8kTN8pgk1khrSy0OpzWdUUp9tIPfr4woQ3yIVr8LjC0r3tU7o0QcNSruJsK0q2bxoiVfqV1/VMgmyIW7N3fWCVSDEa6c/Wh1iZRphK+mWNHOr58gSA/cUtU0wuzYbTJf7fpx7Yr39cemBeewYMzZgeWbJhaF90682+ZWyYdtyuKfLUcHW0dCoyS7IWhcyAhW7FqSVZljGxGBaiiOPLGCL9dbwyNBy8YcUMea+LZ8LIxXxwtn2L8JHFKXW0U/UqOqVXyB5P546idWsU3HVIYHEcA9xMfXUsjE1rAa6MNA++mMy7SvCt196+zgDNPdyzN21dLeDlcs2RY1eS1McNl/I3XsyHTn7kj/ky0HK7ShRgj2KNQL0Hx/tVXqqBLw4Yyk9xS9CnTl
    github-token: AgCjQeFSYQq4iJa1t1b4lRNK6zZrVuKfruP4NN6X/3QbM2h8EJxrO8sKQLt1N9xZzYNK6UoW8imL9ic7lgDT1i2SXp9RYCKjXT15D+Q+fAInAdHXNnPcqLC4xXjdcSJblhMWgk0CLtMLEde2CNWdHF9OkrsbGwdW1Akwfor+A7fD2H71+4/3GabFV7C69+ONCla1xuS7ig0nOYLoiL8/jG53u1CXiMG6rJnacSOKGoIiNT+5bktEGOGsHsa+78m1/cY9thniNhWcvIX6aP+63mKnmT+fIw/UqiGe4xgw+yLvUQYCFgd/8s+TPjNUcN2/mYDmPtONs/GU6mR2xmnVcH1q8P7n3LWuCzClnxaQP/nmOqIIaAO6TAITy5jT2T1hDkXBJ+aVCz9l0RGNNvX6+nZANzk9k0JvoG1uGMmFPMZ4bKaCC3X/pY8XNmKPQhyauQwkhdRl7VCe/aiLzO2X0JUmAwkfyjROQdh4mDRIPRbMs4qTRJJKYPtcS8OGox4fQ0DIFB/J8bQ6DIXoX87sGv2kKzuuQwZ6HTCpB7TJTbck3OaaEX1DowN3Dh4qRfeRMG0wlJNrCNRCuQdt2DZQNdaDO8eKeVRGrbRG8Ag+b7VU59HzOcf8jPh2TQOaUTAdCNK5Qf6vcpgIhb0FS6Osx12+PesWDHstH6G5/v3yZdMyIT5zdsbkkDErnLAHK4lbYjrUdJdSpef6ii8fAkyDW0g9F7DITeKDTiGhliKsa7hu1QgZUfLOhDG/
  template:
    metadata:
      name: tokens-secrets
      namespace: gitops-app
    type: Opaque
