---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tokens-secrets
  namespace: gitops-app
spec:
  encryptedData:
    circleci-token: AgAfAoh8/wZSied8vx1Qp5nDfxSqUxBRjKnr83QdN2PiF8zbWhwqSf+n8+L73G409g92b9mpdWq9fXVxnIHmyJxpR88wA83fqICLuc5J0DjxWOXBy+81DqleEmJOnnk5imAZiUi8Ucip+wrJgOorKBsqmaqAFrCOA5cAAf/K5+Uk5tkRchxlO6rZkDimmbAcU6vrGu0ZVfQLcKIfHyXwGX2w6mYX89amg6x7ui6v2UmUAS7CqUDXGxvvrDBfm5p35wwtTGua9JMJ0tzoq6AW5Zs00LLJeMIrKUt0WDNyofeAGn3AqMT8FNT+AYgTzB0EnfcJRbj8vUPoKDriZtaLM59GHJX9xwxvyLn2iBOW2KeR2AbawS+QzOTOzypXxP0XXoO+wRJdo7yx92WREzQhxoABvsIGqnMHz4soY2EP9f9hTNJRZ5DgJ5z3xgth8BPQxqup5RmvRAVrhlr/UVEMHAKu+hJzHgKJOcZK3XsYpqAARqzXQ0mR1cEnF9EPn5TWkRVv99lHnZaLFOh+d1SGikc6n5GH/ufr7ryfBFTekG0D+ZNrWMiPufepA0cyWciVj4oQRmQ3OZJ2iN8Cp2QISWCgbJB5PIccjL6GW6dWEBXppffxwQZo1BaSd7XZ90G63f866v2p32VqzOnHb4wBqTTm0MeM4j3IcCKwRS34ExPZBHWpipCUw9IHmmVJQ/eBK0JrYssBC75dhwM6kBp8IBg1tvA+ypase9eZXgu3R+sN//4z4ceqf4DfuFUOSxeXp6BC0AGg7xCWFYToluSmi7/JKlL0ae7v
    github-token: AgCV4cMaFcoTUDTbQaqQdTckFEynl5ZtzcQMPMSVYqXFAR8UHsFyJJMwoKgC/pYGObVUsSYUj8c+bg8Cn3WpyYKtPAswBHKiFlsCl/iIcQDS++yzpddQimu5WPNKonbputib3uLdCJKdXRhzrjUES1BImICNJBes4RN8kZAtdwPv4oiOlu9v2WKQ2UmOvjGvG7TVGJJNMulsgV+zOmRbXASj1G+MzMsdJhEX8KMUOMC+Bi6LOTLyPcGkkvCVBS6EiZ/FZKuj4WsOM6wGBOWN5vJeb1o2WyBBM3mAHbrDz0yncS5FNIo1sw9PXQ09eIj0rRkQWIXF7x+6sTxjFPD7PQIK0G6/hQ5/uiXVtl1enJCFWWgVg75PKECsMev81UmAs0kYYWtBnYl/N7ytCpMo4ANsagju63+nCVpMa4HJ0107y7Co/LdCL8JbYJIzCZmgrTjRQHVX5s9/mFK3Sfia9mNAKCEhToVaYAbzXkkbi/wbthrGb7kyhRSdjkyCYx82LyQKFDgSDdjqjiP4E6UqmDpJLXBgtYQLOTwNcvswx+u8msqOIxGhgkwzYNHV2GsN8QyUH8TXKmKPyVUpNDl2akgM9MwuYx8R2h1aUM7xEPz0RKhGBOhjLYUK+lioqgeRdlTPR++qy/VAWhQkwcVX+CE4y0NTYOlvM7Pm2nmmKV3A4sfXqOHzDcr6Kb9wZixQF5BuIzmrtZIuVLaT8gCllaUHDf8AsofWypjftVkQdUCtMM5ITgNo7MNm
  template:
    metadata:
      name: tokens-secrets
      namespace: gitops-app
    type: Opaque
