---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tokens-secrets
  namespace: gitops-app
spec:
  encryptedData:
    circleci-token: AgCkbMqOWTF8KagDK88LVfkbN3HcTttiFWP1uemlNIg4UhxMLGV1sxylKUHj4HofZb0DEWislUaUpCBVwuOIzkvd/YLnNkmT8l4NFq4qStDwyghSm6yYJ9FzX2jhjApAfLq0nDtVdgepqdPlY+vykeSMbpkv7UK9CU+7fKVO7exDBpB62eSfbQN8pvka3H7JghxRYS2vOSY/DDbipyeV8xkCIcCSjyGzob+low0CoDsqFizsvFONsnc3Ta6ygDJtkZtRtHKbdYX4F4WP/pxWg690QDbPjtTcoHyCjhUj1CUkV7ChRL6J3aMSZtxLqOt96RLrFrySX0jpTsIBRaKV9sTv2xG5K338cKLTtWXxf8o9FZTBzZ5+85EXSzMNNs0F3qhGT3lSEpCCNLD4WFF30fJxL9pmNZolJYAxraLuSFdcrSXqvoGMw23H1M9Ko1kXkwyhXdYzm10XWnBUUXHWLHBEoYK+6k9YkRuy4iaxEsed67eICWG+wYXwpgCru1Du49x95CKBM5oQZFRu8cAwx4yMxx7olIu2mq7WjN8R+ddyyzj1AyRV0v/1zLxpg6KIKqcUDcGt94F6ih7yrNjkXUzK8VrjrwrAL+OhpcJjnbJ1dFug2t3ius5rzCsBANppAxuIk0FXJt1EUoMBJngglc41q5kcnV81OXfQeDigFcBzDPbJoBFrylZPfPH+jUcX/1Rn/Hj2OvJnWslYvz9rbTYTZ7ZHA24eiZaFlC41Yw7l01fOo6CGULshl2jI62aGGj09TDEGeyOQFVnlEGtwohcj0jkau03f
    github-token: AgApnqLNcZe76GhtmGWurKlyDOfhf/UIe+o2Ha5K3qfDafqkPTYtgAXvdBQsIVs5MdMPY4ypNWCjUT1DoglpTbWbZsQJlR90N/JO1sqzXZcqSQ4ZvBGjcz8zdG7sDaMl3RA+utH/5jdWdJmvLRH1EdJz9YDaw11O3WtGHW+iwoLKyzNm6VBIa568xVrzRgUw+VHVp1F7jPndMgjbIDk8ZSa4+4Gf9bDrGTHw26XqbD0UdnkT1XfQcqKRjsQtnwXIYBSDkNx2CdebznpC+mNBtkqqTIOMP1m2hbsx3d+5oGHA132H84w4oqWn1KOKjRWV3hyXaFMXlAzXg1vBSdIPQ1ZOHVzyPo1iownsJk+mJoLq1N7goGYzeP27OR4YOQ3PTIW+dIsRBiBOPRJetWrHibmyHkYgM2MDfbI8wiclzgDGeTGdpi3hhzGC6315pn9rmxzyJ1zhT/8yIq92Fdlcc1Efea3LSOZ0T9Ql9V9OvKU+jqXeFTMRy7w6SzkWJX6mzYfc1LC9JZ1aIAhya/n0Sz0CfNOY2/8lQB67dH2OL7JSiUnClxlXgtpPaKruoS67dIc0QTcLSOumiBOjwSUnFfgdOI4Jyy/PNIwCTuAAZcUCvZy/X7+cGlCjq3qRMs1dDJC2gOyTqBGP7+pzUBxX8nJ29Q+tmeZSS8dy6sri51Ce4mtbH07+1T+8dvFvJSymyzcWnZnzAVpKbqlxwpLe6KWza90VDMjzSUuWkFvjcc/8GXHVdQALNuz0
  template:
    metadata:
      name: tokens-secrets
      namespace: gitops-app
    type: Opaque
