---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tokens-secrets
  namespace: gitops-app
spec:
  encryptedData:
    circleci-token: AgCSDCAPBDCb4LxIwkcfgsG/AU+JmfOmafnqF1CgedmtT4veX0CxmuB6+BmYnupOKUsnOG6ZZ8j9ZSmmMB5ppZU5B08Tqo8e6Ld6SM91Rcl2um60QN6wUx6yCNk7QpFNGTs5P3JvPZPk8+oVJ+/1xNLKLF2E8mW4l7y7h6BWR9QrCqIkWN9GTDrj8TULlaZNP/yieP+MKGQhomfbjhsTI3/i8JBhZZEDkS56nIo6MfqQJvyGoSJ2BL2GJ2nZGQx6X9P4+ZXSnRL0h68FHmBUyg+YAnFJk4ok8NhUJU2GJzGgNyPKyF3ZOBVrX5eUbDK+NPcQvrVBcCOoMVOBU75liVL9YnmtC2MU+XEy4mytXUn+JxHarC0LAeUIMr6zfEqaMmNGqzsajymhPM3LvOeHNTa6HS5fgh/XUewP5nHrkzEo1drFTgOMIIOhYJTJBOXjSFV0gL6ArCbRXH8arYHl3jJjcJLdBB0Lc7CxIauMGDf1BGiooQpIIYSdi/56hSHY0Rlotjy+/VsmQbEMM3K9QJPSUlvNb9YhSVtKuFa1z9qoKHqtEJfICxz3ukpMBM5wWcOlYo+BqL8qEaenCx5iNFRMcuQQMyKaeQQ66MRAaBfEQBIkouoIFwge8GlG+D8mh+NkXjf3J7XFNuvuRgCwnJxcs8EwssXqu2pukiOlvYvVSPQzOm0poXc8OGkDxRMhLeBE9Nu3yQDnT7m0MKENTJEYHAiNy0juSOr2IWGk2YNJq5MX+H7yCleVYByyGdLo0mi3zP7+RiFCw8MIlw/tmwKLFHUwUPSz
    github-token: AgBVmKA30MPpwbLSaE1ZrQ8XntzCVrXNSg1EnWV5SUYSQZq2kaTIZ+13HrpmM7hnLjylWGE5SYa/BDS5CNapdxDu6Gb7aXGRTJWIjasdilD7gzwGDket+u/3Ts6VyoVoFia0c+UFhb+KYyIEYA7vBd/LRrDwcQg7OtEH7qsMIQWLDcThINATnku1tBKYAaeCHWxrqFmQdWUbtpJ6/IkP60FYPsSnKD0pafoyCc2fMbf+Lgj4f0o50zPbzURqLehxuPWQVoMi0TkVyW8NxQdMRvtGWTTRBnTakRQigFxzTssGlWl8Pp94FpEIjBYWoO4AXW02BvWKlWNa1MqiyOclva7JZ+SyqqrusrKCQ7TPiIWIyETb5QWqUsysUXMSbI2fQLrbQHg/UV0R64jndVQ8Am1nPSe0LDPo4wi2Cohr7q4sJAvb43gju7jwUghK+6Za/t22k7kQDaCIvN61WZcyl1DFBnEUKxx3RQt5mKDa2FXPQUCObhMlhVpDQqkq0fjubjiADxnti2dRSFXWbaVfUXJIWY+cWCYTwn0L3Wo+IELJbiTAWoQRiAuhXFL2NsfUG+6hNzLv1jiLMt0UEiIprVoiY/NseX3htuRYmcbPaSCBNHJTLG2+DDk6cZQB7aQdzT6H2Gemcw0NblUlbfeotaSl8SHZ0jrxKdkdepN7/QhsT1Gd7lwdOXsemTfro8q5dQ4LPHNlVatd3GN1a663XHQKc9fo4xFg5NmjsTgupPz3xrGkrZlapo/s
  template:
    metadata:
      name: tokens-secrets
      namespace: gitops-app
    type: Opaque
