---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tokens-secrets
  namespace: gitops-app
spec:
  encryptedData:
    circleci-token: AgAJZLOHDc+WNQ8cRPHfr84D9VoS6PYjniMEYUQWNFeBDFXIfGmAxQIRemnvHmc8/GQLS/VBTgnUBYzVGCp09VcxMZ2hGszkvQ526aUOin4WAWsRGG/fGcm2ttxMHIq0+6j9PVnX0EQBYfGRL/lC9Ub5TwLnQHKOLkKx/Mq0/FJIzylIVznpIMwvGLmWDrGlsGiDcFHlDo6KI7G/85oHehtMzfMHgyyYc1SrJAISdm5RL8hgwMz7NFxfyTYSYQ7rqXGOSbolownRygN7i93PMjpK7/jZJFi6YJF00DRwSy96w/R3/3+EWd0DiW4Yn25QEN7RqUtfJ46AJCo5jSxyC5No/A9ENSLR99D1996NPrMi+lBDcNZiNOyRCI9f6x1ifh2fW9k3ZMoRfAKB1gdSklw9jGLmvJXIhuBldd1KiwFfXoyiNqTnV1koL3XsnwzrjUKI0nj6ojCo4mKiEeyrAPLNiZcB3mkLJKPcBgr45srwUZpq6HVelqw5sTi1Z4750KnO8aqi6TfheSc/5mXkMYwBiZIe8TVkBHWopRZ/VdV/7zW5Lol1+2hNjlY4QRfMAeIl7lZAcCgM0gnwx0naaDsN9zwwMCDXli39j3RYpnYmZMzL2HD7TKxEyfaZQpdoQRjokk9voaEro+Q/z3O4D50oLK1+M8ZA8QvcpnJ/fE5eMUscOaP8TuiUW1ZISKGRoHqDYoLN5sVdmMzDGiB78rFl5YCtKUnGglaOkXYA17M1+tJgtTp9V7ZgnQbT06vO68T9R7YHtP2CuTnXhjNo2Pcp+HH83+OV
    github-token: AgBbmkGb1YBt9ee7Ea6/Yq5Fh2RX58q0TzQOzUMo6mvQ3SzuCuJ5VamVlq712SbQ9ldm4laCohifkpIqZb7j04pNBGHSaXcwDkU5gwpsJCyApVPQIZHWzH+pOf+JDahaQJTZFqvfSc2BBbLhvPARztWyCzH8SqpvGvt2s2/mAkaSFdrrLZjQlTTWDL4K3iNyXqNKd4kO+22l7T0z2Ez5ci8nRzOLyoqswKIrL23q1UZg7aPAnJXru/GdORSB3T9G1bX9JiBAMlR1+5PWqyuJdm7xrxNSG4mSMCkPFXcbsFu6azMPcco8sdYR6JcZdoNpyss1+6pG7rOUVdLz4qGWLLrutjjS8truC1RYiO+iIMD/EURAgmr31hDc0i0xUxfBqPCLkJW0LXam1/9CStyATq17bE7ty5WtgBy1/hY/BXNSl9b6AsR81ie8/uNOKBOeWDIL9lC7SzEnuEDLHQ6LGTn4Y+KJLFtfnJuDeuaFz8jWbfumoDAK8ytOEorCc8oQtCWKs1tudVRA3F57BVcKibMAgkT3cZjdR6V4rlRLIYP73WM2jxZYmf/5tAhcoWiQla/qIS01JMZLCuTLAJkWgkFThkKr0nDL/QkvoA13Wvb23oX8p2SiTFm68h5FCujMjCJM189hjyNJdn0FhbxTIgDT0OtDP4kKlTNSKp+qmjtThh1+QD6KlTmS6iufR02FIt9i44Zdsn9kQ5auFdYyV591ykekEMISsEuYgLGeEZQB7COv9eHWy1jN
  template:
    metadata:
      name: tokens-secrets
      namespace: gitops-app
    type: Opaque
