---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tokens-secrets
  namespace: gitops-app
spec:
  encryptedData:
    circleci-token: AgBqenmWqn61g00UtlljGX3oU8jE8ggq1ISdPQWE7dIcASJp2vG7zgRhPm6M8f0KLiCqBKL3SEeP4Fb07JKb8oewv1pEdKeWbox9NqWk5KWDkOFMmq7Ro1+F8NECkYevHNtTZ+WrO4z3ABExkvt3ZYh9oucT1lj+1HpKKQJyw5knRUUAN1gzivoRq2oS2AIow9bz9cp0Q427NMpYdUuzxNnR53yGrjKp0WQMh4T1DWMSpSvu1+WkXxPdP60iKkDTm2IKBFXx+kGAuU5roiLVCdc5yFFfUwjxqzWSHAQpXIIeDFpKiJSM9vj1gMEvphRoBnrUct1/4RwtNBo5QmZwP5R6fZZDretx2LGMrO5VZtK3IOh2UQo/MbTcuwPk+EAWF1d0QgqbITEEtK4HkmFYB7yAa/qpG6h/6YIfWiBs31GgwDCSjNY6Q64L7Lv1+UCE5CZ1hq/Nak60GVHjf/UGzYqjue7Byo8NY2gXannZl5PXGs3z6yKIQ7HrQIRY49AIiiZQzd6ntdCeYbQPR8SBDQub77W+xcUgWybHgJ3o9RkBAQh62DxAkhz0Ao6a4X4j5WPQSHI7clwpJ/C9nj5GzaLD4iILbukloZffc/YIv0Bu9gEjcJpaHWM0yroHNxMMsGcu65+Vm0K5tBuvYbwXQAC/6emCBMEu6IXdm9TtWQBfUD1ihQqdiudIaUE/tfvV7pHq148huco4CM9x4c9K+hjcW46YwZcmbZlLjKF1o+EZIzV6ZYt6wwE3NiREXEThLHFoXvs9talv0aQAWDr4JZ3WPcaWdrcr
    github-token: AgA+QInb7z30hUYCRjyydC5RbjVubziRroPuSpmyuU0VRller2OeRQTVCZH8V9mnpaFqqdfQa/82QjgYgZRVDydDONgR5tU803N7BQy9f/i5CHqqGLdficcx8/iWqOgj/qzc02JME9HO4BuPF71qNuA5WksXUdp4THw3IiELawvxJMsJPkit5QGtC4xE7hVlzCaZ97byUTqHC+K63nyc8r/LafytLk0SQ8Uiy36hhA+6qPXFatZwAE2SC20q+ld2cavZTd3b0g8tOnWYyvugeca0pP/+OOYyIDUmIVzd8aLXjG0Tci/ME6MFv3rybPUH1xxSHPoW+qeSMzyyRHaZ/pxZcaQrpVrmKzZ4mJfb1vqZ19fkmDjV4Dv+zuuMNZk00hNQ4xNdAJzH4QugSCOy3O5Z1NgPcEFK1FLr4I1XUQktKU2qBZbNepb9uDmy9TCqA/xuvN/Tzn62lbtdD3WxQFKUb+n+6naz8/26AOtn626Ea7bXQ8OqPZ9zCn6ct9A+HGrJe8Mlk724CYWdAMDkQBpqFxmq5GdCT32iHaZQ9xZlaQjZdo7SXQwnbAMYYY/9TDN0uiJbQEgVPc9adjhTtdwekujuvjzrYj8l4ximM3ulKZi4s209uRz6H6atABoh3nKLMQHtTYuR4zZT37wf/wdBAqQ3DMUJgCoaWvdm1m13axGavvwLE9HjPnAm/M7e3Ttxb8+nq+HH9h/MUlrqiw085qSbYWoEejwg372dEAIfU2E6z17zVuKU
  template:
    metadata:
      name: tokens-secrets
      namespace: gitops-app
    type: Opaque
