---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tokens-secrets
  namespace: gitops-app
spec:
  encryptedData:
    circleci-token: AgBk0EpqvOXPwBg3QspijNk7nErGIqoNkaabjCPxi7Uu1rcDWaqSVEG16p1UidIhcTI6UraE0qJsNnLwEM9NTwfA7o8395ZFD1p1+oFoSkyawim+481DuxX8u0LEXNnN5nXhOde3vIvJHddYZ6n2cmPUCqtYLuHN7yRCcqMd7GnPFFaFTmHQq/TLooF17sUH43YIUFdNoDzVDr/orDhzw5TOLZVf3Sq4XK7Tvz9aSBnGKuB86/q6YZQJKNttizZioNIZyBa9tlTXU2eRmEu+461RMmh1ZWhGIENwdDSIfx+aiCrWKhpJHTHQqzQ1k2//Z4jb174v26y0H7CtZhSqJrDFJNwPFtZT+lH9s35ydYswmtBIgXmvo5/7rGqA0PJpSmnx4dEypXVUkXoNk0awrFOFqPnzCTm2hZY3CoL8a5n0QAzDdMSdfhfJEalmJg3F2ACC1yDspMQ3F4iX9rz7x2AxZet9N/JqoE/Otcqzw1Xyd+j+Dvyr9rLVBqLLeFnmgB0kRqDpbnyHESC4JV9QGbLwMUUQRRF06KPHtcbXOuHXrOpcpliubAevhDenP7ei6ZjLPV+0ialp/ddbkWY9vzTE7xrBFgXvBFExj26MmSApZfwaOvINrJbsjrCT61EMYUZclQFVrUYjNNeX6sfzsTZzf2UVImNAjoKDl2IYFsgbY7gyHSyOs/mKzPdU4D0aj3RdD7WtbeJCUE/FyYtbMI1T3/vFW5UH5yaDchbzzhkit3xy7vH03yNqZ9/iDHQEQNnHCOY8htdGWbEUr9wA8MFxLw6A/05M
    github-token: AgBVAjxTlVPD7mZijh7zhwszCLjF/YeYUZ796DSOJinsWocykFTqF4fy54uBTI76S4uxqfgBBysjSsWMg78vO7peUnSq/dFJ64rXiH7qvf5CEajtkivrlms5QQoRgddQ+jcWat1G3KZEfUS546p98I/yDusc/wpiwHiNyu4B0CQ1dcx/G2JdVmgf84KpoDI9CgPNubh4yl/nZQ1NGL10gX20M6IPjadVBA1pc8UU5lz1xMZfPTrHYOMPiy8jPX+4YDKZokEHfouFTYPfVbs8aCO9UFgv8w8Oac+HHyNl5fYiWbiaQNl3I5Q0/MkH/+H8t0EXUfL4koUXjzLrK0zyRBCn3r0/dpXs2DjfyzaTVLuH/oX4lB3P0pDPyPRz+xfBAcmJZhLPCgfs5p5tBPCunRh1J1o8dKsveMWo7MYVF4rPu/SxTdkJcBcR4Coqxww8W5Y5LAy09ujw8NPsJFlydURbDXZSjCyfHrObIFPjGIAKQ/jvDoM1rhswG1SJPfle/zO4+NDPqcqVLu6AVmSQjPrzoSxr4I+LP2LP6PGN+g9NYqkaeRSWhqYV6Lz3nZl1f84J9lZnydR+Y9rvtaI3HbQVUOeIWEegvWi2Uk36qXSV1FHOA5Hf/xTZF/96K7tDHUMmMP4PH1XtuqmWW3nsZeLj3EVd8UDWxXGOHSub5deii3LoD/+wGFCjnbUDTSATtPy5t8hdqrI32GzFZghdzwbNFpekejdmKNZ0LTDVmizE2egfcdex+uTY
  template:
    metadata:
      name: tokens-secrets
      namespace: gitops-app
    type: Opaque
