---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tokens-secrets
  namespace: gitops-app
spec:
  encryptedData:
    circleci-token: AgBHQK1RAP+uOgquVGEbG64lcj7flD+Dq4pjIHr+Ha14MRihUAFtUYtz+YvA3UkYgWZgRHjkkrPnx21ns5wrgnVUII7ZYW2RtFVpnbVJRIbHG+kYnP4EDRGk9VeQC9IbpUnnFQMAHXomsFmURRCRc0aj43ZyNOdAmmEi3zI53bgXoGTZgR0eFa5kWgbjHDN1JLtEQZyR/tznEVdL4STcptkHOnLUv19Q/KNymO4NbCH1eE7j5QYcRLDRAMiAcGXnfbAG3FLx+Dv1VdonrLNpS4xMKwmSQ5HbmZ1Op5pZFRfvK2k37CCYocyVCh+JkbvnW1phEUS84y2N/eb4AzncV6wPJI8sV2RKeRTLoecydotpOsMHHQZNXpWfgOdZVfFysNBYuT4Hp6WCmzxZWxWLE7onc4oZLuuvxyaFgbz+GEk6aVkqw8hMwFGcuLi8M8SEmuygw7Pdd0DhovwINeC5CX+U6ImC8Nx838d08zSYAxP+dsJZZUcd+LYApV2+Aw8TNKQgS2UqEXf7tP2m/8bB7QjtYOd3zPHin7sdFwLMr957WMmKwE72OKo6Yn+32vKetJYJPfq1Ae3+wK0qjQDC6W0Z6VSenxFU+jnIg0dbYiDqUUfXod33CGrvj4JgaVGfhU5Yllwt+HyDNB2S+5HoS1t3K1CS7DiJMG7XsazIGc/gb6CJiyRAKAxn7VHzNfd5A/u+ztz+hnp1X4GN1iHCwbRgFU1lT/iHMyvYANAIq2trnZ2AOYDGItrQ2s1e/7S4Ago+alRhZeWY61jfT6+kmf+ggslnFtRu
    github-token: AgAa5KdxineCDVwPnNQxIo/Q9MlCYqpnWATvHMcbOwJdXzBkk7k/K9G+ObC/QRLcdKRMcsS5/Px3muHxnNbL04ZusUXT5Suzjpte+SaFdgVYJyL72BtwUGAn0cYUNMEEDSIvIq0FRykdiswKWwX7Jg32QsY8LmGpDfGA6TXcrlF43yneLuPqrJikN2eyier0Bgs7NZEoYi+W1ihMQ+8wtFkEcIooYRvEPudaQrZ9TlR+nbhinVe8dCMx/f92HxHH9QgTMhUd07n09YcczKbOXNh2Ry6db1JFkjXx6a+UTtC0uuUBUsvVNyD5niIQkfXITRIrs4i/aan1rPUFX+Sb2q5PdXRLJwFw4HQ4osOHqQ2+IQT6Apt8oxUPIINvTktyUoIiTIhXUEZg5DkptriD1YeU0vSR/7zW5ZcrfqMUN0vdeRl7gSJx4pPWn5TXziLdBV3TFHCd6IdmOqBfvrhk66aTVltrGb2hiWfIVlWc5moXoX35ekJFXzAVkKTEkLphenzTGWM/V2GWSmZy9oqFpWOeBP6N4REBHDD4PMxowvKBnts+aYCdMoWFY/PjWk8S7r6Ze0C/pZbaMKOF/62dIzWUPOGsnNsVgr0NUtDDAMsSMqZTDR9fkDc/yMs0qd+oG7auEqorIyN7Jg4gMhhypXc+4PYuC/0zRPPgelQXQDdeptJSTHI2/YnriBL+JkQ+BByPJL1mdALlu7AR7UsrzWYcsqPmIVL2f689Vvhk22QFkxzLRDrilvsJ
  template:
    metadata:
      name: tokens-secrets
      namespace: gitops-app
    type: Opaque
