---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tokens-secrets
  namespace: gitops-app
spec:
  encryptedData:
    circleci-token: AgAz0urV6u22xlgy+hghrthXaEqdNZMBsj8sQzgQKqPyRogvnrnsLDgcdaHphNLlev65e/FeX6Mqoi1fgCHoIa7vhfRK3qwR+cZl2kjeD6bLcjjjYZJ6fGSvH9/lMcoVJ8DeIk2NdbV9wLX4uHsUXmFDjNxUGnptw2xKx1nXs3096Im0kttJlsMR6Ns0O3iq44AUBerzN+LiM1vQnZlPJddZWZZjDssA+M2J3tfJ2Nq5KPv8eNZjUmLLjFO0qyEu8mPmXuvtyfN8oS93x8nxNPSH0F792U8OR/R6Y/j3+MswF59dXtFXrhLd5aYj87O3YR90mBKQIku+oVyV7iBGTd6LG3TZVlz1zYBlHY/nKGUAHemBVnCGIRsW7XnzSA1lhxCcR83AxGKavErQ8RWoi2skrOSDlQrCwobIYslcGyOr3lvzfBGcdlIrMh08Ij1x7NscU5l0vocE3WKyqskS1YL/UuQpwbfupQciOUDQrDNRf1Neco+PH0DBbJZfqgxWC88fFwM9bT1XZHw/oRQqmc2nmcElgkRZk/SWOG22uFk02HTKD+b6vQXsHMsOnhfIdi5wcWNLFu0oNDEPzUc+jFgaIt0sjlrsdlYL9NGL+yf0fJiIHCdC/n0l4joh8F+Rblj/XeyOrunzqLvyUSj3/X3bDc/VLcI9CZ7KcBu+MeHzOSM8gCy8kI7gplY0iV0dzrAT9kFSflQ7tHT62ZqugZ3EDCG0lK/Zg7nbPfS4nZU+QNwEga3oFAA1m4P+skBYpTQCanXzG+xIBlXNFXTuvuuM8qLqonS9
    github-token: AgAgDJU6Ta9+UGIgOBnQpoB2kO5rYKo4n32VBTwI7nLregdJhK6S22FXO7nrKZM87RXGAa1B6V+3Ws85mgWbOLD/JJ2clhkX6LfqMeYBIhNivSmMnShjpdTVkoPkhWiVDytkVRzRD2yv3zp2wYCBvQ4fnib/6lbD1gXn+H5fVNdrttRDvvKIVx5jNLniwxd6AaR4d7K+mYHk30nGRF+bfE4sgUlDxTdWs9xCKi5XobYWyveg33szSlioRTnJJf17Yl2ZndUFTLrl8VMDtOeECrC/SEJlPbnnUOOxvg5BrtZcaVIys5qqi/Wsfby79URUfABJUqRFcyNg2IOD8PWg8eIoOrtLXNF/5a39s9/W2ooYaWsQS6N4d1wp+JtDX1sI5BzKQENnpT2TtbEoZ7ZFqUYAte1WIT+WghCR7+lYKR5EepsoLUv9/9dY8n0rPZ6ZOxWRyoyNGk1RDvM1gxLQ9DsOhlozm1SBAHkeAjUBRvzpcPoz0YwdhccVRuedWSGXXYNg9ndgTqQA/NYlBr9qlc5pXv0UqKVZEZK0A5DvOGjSG0ygaXZorImocCmQoXejQvi0v+YzZfWbynTG6MdyVS0hruS1yyj1uFCJbfaA8j9wNSkzq/2OrjZ6nSJVbrUIU4bHwbi23KrNo91IGWmLYLeEH5E2vi8i32gRuip3T0IFaUf4er1qhYsFiW9dNRVSz6QubfQrF/MkFQVEPltDa8xJIsG2d+249vzCkvauWnIBIj2zEspwaX7e
  template:
    metadata:
      name: tokens-secrets
      namespace: gitops-app
    type: Opaque
