---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tokens-secrets
  namespace: gitops-app
spec:
  encryptedData:
    circleci-token: AgC+YuVzExahtPcim+lORYVAbEFry+U5V5nCeSAQWY8bpDoCQP//s/fOdoKr/e6v3laKUU+Gct/lBlFLXK2tFWKgP7mkJGHCsuflhcmjKlKbsi+4pU8e00h2UsSPSlb5OP4RDxG8d6rhK8knUqRctLgjza4H3VUJx2tjFiCXniekLG3lSPUqqoVjZBvlPaJaGP0ddZpbvxa2qrFxwyf7Jh1V7LDZogTY5M8YgwHvkC64KfJbqaE1z1kEYXE75gL9gglTH9sJ7TJQoC/j3zGipLoJbQ3GgvV551RBeF7QKqAxeP8XDz4WVUmXaFB6JS0r6ToyBZmpS4+JI1pSUqvuFMCZNlv7ktEPDXNxLHUSdO6V/WQJKo/W9txijoIDXdEuJlANkG0PQ+3duwbwxPlN5NGYFCph6i0s8MeMDW6Zrpa2XVLuKlEa03z9/PS6IPrL6gkG8AmjQFX2wGkBJwm59/oRHBF5/G2e7zf+bj6X2WAYkBVGY6jJs65Vk/5nME+6rk6mT8FdYgPhWQcOiMMZZb5XT5vQC5RPk8cBDgpIw6AUoniEcrLxLhNvvgJMsFwpO3/UFgWIxyrjlZmJWVWN9hiQa4hAl+X/tOm7vduFFKadWubD7slyJ8J41p0h3usxP/PooN3dI2JHOLl2l2VJ6H/EZwRTA2nOs0o634F/AlYRmrsQ4xddKPV+343xG9v9lWclJQx4X53GsvvqTGG162ivM/3qfov79oRwirYsK9zQf5fJMVUTK8lYmsW8swrw0wK2l7Jnqs5neSo7pb6I+Xejj7Hm1W13IkMcHw==
    github-token: AgBOs01JBvz4kbWaPPhj1E0BsTKTlmQ2Nn3xxBAu+l9en48GlGBB3KHrB3kTL3mfqKuUKXgyWyIfhpcUYewzf01cL2aNBx0D93yYso0zuqvG7FSQeHIdJUO8EVJJuOEuo6861M0AGNSM37fkZ6P4YqJGnAacVs0N7Q0SzkMk4kPLNJUy9kMYX2AqhWeMfWYkCSh8+4MtZXPxHgmEZPaooo9ZCqI3dqA0sLblWY2tEn05Yolx9ZA8Pu3lC6MjZILeo2YnyILUQ/XQq64vuPC7j1tzRKhlPXT/7wEZZTB42ft05O0+qDupTSmwYs6pzWfFBn/weHRWxuVND9q7rAlftw5wRpzaRpXLAZ3NiyGeb3W7ApWZON7PtmE6BXEsZakKdI9us1XAhF/fiY0Ygw5rfnXGG6AP1hDXLvlt2D4sRYShglAM2GptmS1YH4gbqF1XmceQXhER1JThgiUpzCdoRvnGaodjkmzOr0qj6fbBVAE5XtodUrriiSyVYqE7p3LqK6UMazQxjDpnB2bCgk6Zm2yqtwI/R8ZYd/BqDcXPJVoItXzvQrBt70jbqVzozJV7ZNceNtQptP6EYbIWmjcROVi8gxZOaustlE+xoIBacT4svavJhwyw2RXrFqEL11CAJ4CYJyxJUDF2OKvWGU7iLXaie29O/zadT3X4IEup4nuUNGOceFsCcOy77EAWKueLmpaQNFXAqV1Xn0UNItbHQa33CH293Y/JhHQh8t0roubVvVDv4W8AcrvgEeUeQA==
  template:
    metadata:
      name: tokens-secrets
      namespace: gitops-app
    type: Opaque
