---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tokens-secrets
  namespace: gitops-app
spec:
  encryptedData:
    circleci-token: AgBthJJZqLS/0f1KPZ+bEBqHZTXNtOKeEKGQD2RAJDm+7mvpWcbPazOWmZxrR3S/s80uY6B8AqyA82TcsMrSqq7l8k401ukjPJ08mct9NK4sw7hQyfPH5vsbm2kK+EE7ENMJS7/CtDGiqMBeYYP/FWQf3vsY2pA3+lKrD/xQhf7lrh6qYP6mMKC0+hMiUj0oa4o9Wm7rigVR+cPXfW8eEfGhWufI1TiezNFwWeral+tmuOHIAuvsNEK35noaJQzZqS3E9Tj2HwqJNu3Solr9/tLCbZlIu9aByVKUb3JRRX1/ivG4GhbukVSfPNpqwRNChJ6AigDLkVX6BkO5hqxwabFhLbDm5Z+9PF0ssA7FmMjM6uSB1zWeU4t9UnpvKkJrT71rnAevruGpjvC2XErXUdz8D+pL0bh02IXi6tCpCLOwOqZEjYcsrXaKv1ZwEucUVsgcW266W7YRPIjtGoWQ9Uxqzz3LhEi8w9MbWEreY0ArNZ3HH/R43NnnXytSDyifQu89SJ0JpydPIzzX7qw7AJ+5TSmgcdJ5Szwq6Ej0jkRrnpoW/qAkDbFDMVJ/LdlP5ZiRvbzFXrmHGMBWSyVhUzw2SDoUbb3mxKZZ3uUpqvCpTzRKWUsNMLV3g6xRj/HkFDE6RAFL145k6Hj/nJBJ4QctY0s7gps7P5gxgrci2K2/ToWPxJ8+wUkVqTGsIPu0rHWX7Npjo695NWn8dCS1ChVCbfmzv6XgaXmC2fNXhCwbncOxy9i0TSyHQwEYBMv7/uvqCkEH0fK3v2T5F+Pcvr+9opsKCT22
    github-token: AgBNB9b/zez48tu4hjdyZx5g+qAYhhArOcEJe6Zf6N2r2ydpVhATip/g9EyR7fCrZeVDV3iaIsh32pPxvvNp4LNcow8cYO72isvERFn6Ji75KsW4jjUVBVu4ko8Im2hkZ1rv4Owb46P7Zh9IqCyf0kI6ZpKApr6ku5xo6zPxr9fPucjP26oLFr3WP8fo1PmCEQ4fMfrOqRFF1leU+xFck9n45kQJxwSlLNgXFaxdeUEbgRHsvVpdnuzols6bolLUSOxmfhWr34KQ8idSrhBNYBBd+mHrC00L8OHXhv97+kJhnYOP5sldkPP9w+Bmgm+sEm/xeyM7ZWVzIXT/DMQfsvog686oGiU2cIDEWGeBGf8B4EWBQfb90hqkREfYj95/Id7qzj4AJeb6Fsg/jT6GfI9wdlSBzafI7vQfvv+XdwUST5XDmsERq1VPNqo7TaHSH9pbqvOhkr/Ss78IbSezQ3TDXUk6AATqZOTCryUZ/Q7t3Lmysva2Tvym1SqlQDGoQP5CuyqSEzIugCARr36V0UzACykCO5vf8FobJYhAyGvE4HJ9Q6+iLgsbfWXi1w5TTt6fnchJtEE4Zyn0VVMRtikS6niot/fIgJjMu55YrCpQeDVZOaGsjF9BasmlRhb83It+8wPOdEJGCQmLjnZ8DmBYqKgZdQIm1ogId+BubUPWSBHT4SOJfAg1rj4YtdOYctJeP3bXi/1Ir9cbg4lOib66+FGIuLiJ+jU32pwtpHWtzgZnuEydNVnF
  template:
    metadata:
      name: tokens-secrets
      namespace: gitops-app
    type: Opaque
