---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tokens-secrets
  namespace: gitops-app
spec:
  encryptedData:
    circleci-token: AgA5hhJdr3OPQO8tHpEDbH6b/PHoWWbeelhhc0Ixjp4tj5H2z6W6BFBtjUAoByRTP7sxuD0bOdsLjUunTvqurdfGwfAPnHMnEbEZLpqvWscfSuwek2nN/2EODIAaKATs41e/XVTmzcv8sttciv6d3eVrMMLOdufCiOE4Eb19ssxSRoyPym9HEMSh1LtAdbYVkK38ijIZ9ffCOalxA4ECgSvXii9mZYywzovnAZ2V5C5vI/l4fuLBs9+tI4+G/bnwmkQAXnFW4IRPnWHe3aoLYy7FsSbHp2v8P+Q+ZMnVqGjvps6fNfzryOHvig2KjZoxKkjZp9y1fid+07ZaWvdLSS7BSgPpINg3YlyJrDwzGP6mnfXgBGKX4ib7IAyrftTkMIG+zjt6JzWQGIFfb4KYqZIfA4LlrxeVNw7s32oqhxeppmOfpXnd5wz57CN9tMX8bDgrTciLUeq58xNxRAA8qovdF7ULSc2XgJOiE9Ay7wI6zLz9P+FNLZiVWRwLq5aGAMptxEiS9HmmBF/6oD9ZetWbPJrM03uu9DVERzqj5nHxi075r8ChUseSFCpmH6DsMSXTOEWdAJ45m6bp0B8pKXaxzwKXYvOYDGKIdzCCFGQ2GouwL+bf75vCMNzGUIv4I10H2ul9KBEJw/OqcuUHWvflTyXbR1+OFt0uYZktw4iiiqNc8gN/hPu9+ODekm/xXqC+IepXOTOlJ8RccDN4YUiW1sHVXZI8xV6H6x2umlboUmYb41iOZkFLiWJRdX32+xkWBpIfooFpFodojfD5ixFmfEKA4MgE
    github-token: AgBxWie/uS4hLqFKPpmvlGKvjfl0fSCxiPn3GJX/9LlfaMlGFZX+c0qq431pQRWgFNCkCTBz7Zb8Xz8cSWYXRWRW636WwXgn/lxQK4U/JvBU+P62ojzytTWe6o3h0BZQ0/Vw3KzCiw+SSBS2kYOyj8PfLmlkXD9JEqxM0Ha4t6OCnM4StRBM6S26ImzmB2LAy6DpK/QkEWcdl3vmyeKQ15pHUynK/aw6U0sX7EDGCxNxRiVpj8EFbQ9y1YxoFL997eaOe41jt0LgQQvfZbh87foKYLRV/mz2QfwcivXReZhnMsHmayYAz6jeK8kBMmVI8cNqnNvuk9Frt/h8wgbTbF/qDqeqd9xesPY9g3DfzGXRz4g3OuD07mlhAZ0wnBmsNfPUyZ9q+f0E9hvoYqn2aU+2T8dseQnxwQgzOf9Y/ta5idsiKashoOf0R3Dzeby3TdNXhG5Yc8xaXuXRzeRnl4Nr8KBAod7C5zfTgdDoRaAUC6WvBrM9mdUjzRNy4OV1kYGJPRgK33KjK62GWS4o1cpWakXaL7HGNvVgZBZ5PUjTq7V0wAdxMV60UgmRYJC3Sm4cj/sUYBLosCUIVFQle5j9zXd7WT3GKIh+k+edfyZcGfV1wrJirOyPoCp8ngOowMRST3E9TAcpyIsgn7X6Ut44QlT0tMUZ01l2quMiNIXRb+zXw3fiP7KhfYgHdzRP/Bh0QnjnDpTQh5NG4zQwqwhC7FV0TN4rEXQzcYmjR4uo9IXwqEKCADoY
  template:
    metadata:
      name: tokens-secrets
      namespace: gitops-app
    type: Opaque
