---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tokens-secrets
  namespace: gitops-app
spec:
  encryptedData:
    circleci-token: AgBX2SANH7pg2OR90YOcizEganv31nvUbeZXutK1wEkwYEwmG8uHsQYmKr7eOr8/iHqu2bvKN+KnESrf3YvzzD7PPbRF9Bquaw0+DEm4nH/xi9DbB4wD/Q2ElEAU3mXOg0If3PpEoU3Rc2VK6TrJrDEO5LdopxymvIz7ogaiSzXy5EqMu1px+AjMd3TEQC8vctGsBUcqPxPC4ebao0h76riJZjMmuT2ftROUTj7VRGqh47CrKHLVkNdEquDrGpI09B9RogAZaqSubBJw5YdCyo4CPOHNjSNPp4oCIa2QWt5zACcoQUET6UIXDBR1oanDl2FJFW4Vgz1GvQVg+5l5Z3f85QhQVJi/zFUDzPAfH7VMBaHlIfTw8GBtWIcj26aySVOWDpyHZQhEMbZhxIiUP3OozUfwAsV301Adsk23MQHlniukCGk6Uh1OUwRF7j1NxqJR6EEhJCbmyjVBhE+Q/sjLQDv1BA2QbEPQ+SqHV641d6tjicAQvVwNamx8KG08Oho8N5SRA43kmUvleLw+V5qPLndY+671qzYme4q1UdVjcyEpRpsU9Dh9Ox6/TrLV79LeAecjIfYv5UkC+JP1QLpLcY73Ws2K+FXJTL6XGdTEHXeTS3jG810TOe5fPwQJ+R3f66madbeAmoZpCUWQhUDvbRuiXdwfeZ7DvOtNLbzvCj4MKQbiKEdC8K/mlKGWPS9KEoo9PFUMg6OAK67B27d3cCe/fj9NuAbSp3smzLIerY0s+iggXcvmARuPV1Bt2YkwTR+rVXlqGMGjUPVEitDGYVw1Idqg99lhyA==
    github-token: AgCLUDTRVGHRG6S1suDPUn3yqSh7ykC9bVtK/6m4wq+UKihex5ArDctItgn7/tSV/4qrhdDTzMT9zUNL/hRgVu7vRhIzqisivgoWs3SMaqzfrZq+7mt+cs4We5A0clfIhEbrROlq4n0mvdyVGGrjPoGmcWNjf8+esATHZq1zfNvvvw3kVC7b/w2Pl9jWziTXftw997rWgMM8Wo+xgxjG4L7LyuxTaFb0C9ZnVH6Siz4yAN1Dgd+2ATdTNg7AWh3nrSsrWDDXLnwa/+05/R0VLEk9VwqqqtiKnwLzd/zAfC+ykwX7dB4lYc+opxOWELmPbLMoWz6/Xxpl+S/ruwFdq8El2YvaIeaxGfkuilnl9Tuh2xAVp2E4GvTSVXiLA2rrp0lQccub/8tQGv3PTG+sRrW0sKpP5+DkI4c0jED09tcTYXr2lJX+acllCsMeW1RYfOABaTODO80uaNRRon8qLHUxVcb36wn8LRj6ZIv4dqtmPxirvBkzZdRCNkDU4K5ynNkG8805sbWl9ookGHFJ8LKACjg4MDfCG9T9RoSC+daGB+gTbk1haz6lfRu5AvobAgIfIEXoLppE4hBeDVO7EW99BqogaHuTuDlwotGfKMhpL6AA4NCcTpSbvNTcGhKWI2+N+5av3k7hrF/KWObBEJSzqoCaxgR+HAOMVj7gqA2Ox7e3+swIRJHPmi9PMww0nJx/kQGKPisY0WR7rqszvW9fO8g0+AVs4tyTmpnXv4EoZtOz8N5lznIDMas5YA==
  template:
    metadata:
      name: tokens-secrets
      namespace: gitops-app
    type: Opaque
