---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tokens-secrets
  namespace: gitops-app
spec:
  encryptedData:
    circleci-token: AgBHwHZiAm/k9VSiXSJFqKfxHrJnbEurXxkRTkptlHjpsn5xbX5cgaN7Z0a/e+ulpNwVeI/mAwi3xUl5HX+AVLrWkvlf9E4STFo/HLfrgF0CpGFPSlbPXnk17OvnM585Cb2DaC2mnG4qar73i9vrvTS+wFDwsPRLu7hmhnlEvgQlst+WG6Yi30tkqs+wT6ARsZ4M4BlobczZwQsbtGMahitMyrykXSsvNRSPpZVDCEJaXJtfjWsLC6sSW+eS56GIyJqQRuYsQ3ySFfDPOJdJHu+JNwR5/BQRhlmblNevjTDpuHFeSL5x3mOXFhMbq4wtKR1QYfCLsAQa5ZpwpVY2UUQSqB7aXeQMLx+GPEbTH0U1Vk9NFX2nCBIp4UMGoJMKzmsP2s51dPZuHA1Ugbm8bDqxLVLDYc4y6dMGHqJj+mUdcM6OKj5MosLwchA8oIyNoCNMnaHkqRQyGeLaf0e2NdxMqYAfyPPO5eIv8P6QhSeeXilZ5efQu1JN+6+fcA4eaTCfRJ+bLrcdrnMRTJRWZhrNcpai6UZ4VTLAWlSKlPAl9RnIrRF50VE3Q/oPR6A7C4x3ZUs3QlTRrQ2+BL97u4AN1sr2XoIPBlxHBfhcB4mINxAVYzdRkTvE5znQqnOhHjmtuc+XJzVArnGDiw8PTu6FMQuwIeMIQ20/U29CPqdNTrdgiTM6UTWJTo9lbM15YbbVIyPWi7i5gUEa5AwZY2iq8Ivkzc3XENmWc9xjqjcfjt261Rx09VSYTdgtSfX4SGPkZG3CVdv4/acPpGGMGvTPsB2sAY8e
    github-token: AgB/hMaDaLY3ixVFL5WfrzA3Awqv5HySleXgfXlteorPxLQGexQE1lSAHBpba7L3zPFB1zL1rXMRWfhHuSZarBN5MoPLt3nBo84/9C1lX+stPSQ8NKjX6H24tgqKHPaVr+3hTq4rWK2C2/tkXPpclUVM9Dw4suK1Y6ivBiXnxAhP9WvItQYulXMwEmSfIsXLDej/M7FuwdzUR3u365XeaKGXLTBYyT95PcW5jHcvN99ZFtc1IyxHN8DnBI8e+2Qi1b44b2dn/H8YjXppPwv0/DcoE/o5RqWOp2tjroItc5iWbgRLLMVl75HeTpCjiSw6SCWDaKGqmolvPUi8lBfoHDoiaNePDfE7+UmbNeRQrF3z9AVKWhF0rTnBSUyHovTfTd8OttQzZhZ2ZoJCNtKv0uXDB3toUHBzQwW2HfVT9C+NniAhU5gDM0h8+ogbERSLPigHF2rdg9I35t+10oK+/FaPJNXpvktmcGl1JzvKjo4zcXeqRzUwFuzxwi3VYQ1wmSRADfFSYepnHvB4PW4YpoU/7Qu2+Ra8YBRDl+imX/Djy42CD9CWnygIphPECi31P0l/iaao6s5cLPZDap8Bkh54HY1TEscJ3ZhyV2Kd/27V/7qg8iTNnYrwk4DiqwZbiccjpZ0sBifBazlv1vDVt5hrZL9Jkd9QxLm/b8dJpatJ3pez6/wg4hyu5o/7JAr36EHnsJAdkEXN544U8cdPNuYLnf7YhXKWqEi1MdsQrwcChDi3WzNrnk3N
  template:
    metadata:
      name: tokens-secrets
      namespace: gitops-app
    type: Opaque
