---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tokens-secrets
  namespace: gitops-app
spec:
  encryptedData:
    circleci-token: AgAIdIm1juLdJsiddrXrQjJcyT361cwahvmjrvmhGDHXN9CdGhM3addiTnS/qXL5Y3gdrG6rdlib6Z/Ka+dY+YEeHv30FRRHn7jtIXmJCe2fyvZ1NoaZFx/yJ78+D4XLzXi7vQZvpfnbzbERLaTDOCUinMCozwkTlkEkixkEH9skNHJ1e7SdsNzn80HrPTypdGArBXXO2W3N3RK+SEN0IWtl0U6Hw+/VGCnqOPtu5KzXV8Z23wv9/ehCixpGzt0OPpPqPBTZXUAqF4KWUg+XWxVdVZLNMu57gao/7JiNRbV1VWcb51hRK23t6GhDhvttLtN5KMwNCYqS8466lUOLMe+1czmPRuOJaP7dVxuCeE2qTL2uxUqiDiIhkOh6bv3oAtyniBPWWidVNP6k9w+dfUO5zD/o0k1bmFQt+H/aukdZJEsjD0239pacS2U8TPRiAmTg7uhJ9HbxAjEFeaXfn8UQdSHid7nRLfrgz96e5zlZCFptbau23OPLAQTS6Ht8BmRs6di3xEU2UJH7K6okoHAPUAEW822EKi00xodfUBOdLJCUCZYWwqfsemvemHr2wiMUb/mrY7iBrhHLPuM4Hm2ATJpusGp4QGg4KB4otDWetHrXK5lkB8SZ193nwCFI7Hh0JlLk0cs6bLSIK4HYdPzDD/kxxidFtORhHNOFS8JU1S2Ou5990MfXE4U+HIX+mJwKFFmMXg3gQkDauZhHzXQnLdMiTp/MFWx+Y8hva3OiMdg6tJjrcZCpmULj+v9/KmM/dkx3sA9qEoJMgCfWWk/0zABbs+VB
    github-token: AgClzRdssQ34GDnTejzywAmw2THBHlvVX27FRJvYZbBjr4kSOvdK45ry/IP4pYdDVnQ7fH9NUoELDFubbskcqJCAkQQLWt3ejUEJj/ijD8v/dxk7bev8pumPsbYJrazR4syThhitbwGS9Nf0YsLn22ANe7Ovg3pUIp5s5ibOaNOXq9HuWWQMyihGsZfhXohJE/ztBnVOrsoDmJGI0h/GVG4ULpKrpKVWIb4Ypg5lXPSvPguDD4LHE2gMpcEWC7ugLHkx/GYPaQMv4KMDdH2SUTtdysVGERMvGqaLwZ6JVduliOej5OYY443NIsCs2iDRTYcExr8p1ZqNBVXyabwq/+8fDS/i4DTnDCZmb3gPVKHEM/Npo3dndi1vdpWdru/I+eKZMKzB1G1ckF6UQd5OyUKrqSXS9geK8egEpGDemoiM1+dVojTA6j2fzbIMNTXlcCUdzVsJdAhduKd6nZm67VMlSM/aCkImVTSDGeo4fHxEO+cMguEtuqUItqBWqNbvrDOWQNuNBTGa+NnWE4nve525IhaOlq4g5lS5zj/Fw3Z2GJcFfpXyicC7vAb2Lszq2FnyjsqyP+iUrkpt/4EbozNT45WSK+nespnjYqZM559qoIH02nwM0yCCJr9goE4qHBDqJ8WvbQqH0oYuWq5uWM4LZLxQyFS0JBsLwA0kYzMTUqwrnt7wx8kAlkuy+nds3TTbt+P03MKvFND7Xh4WKljAn0cI2JUiBQNDkcl/tgeVMVsRdThNRxcn
  template:
    metadata:
      name: tokens-secrets
      namespace: gitops-app
    type: Opaque
