---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tokens-secrets
  namespace: gitops-app
spec:
  encryptedData:
    circleci-token: AgBesyoFldzzLj2te8Vez61kbkzjPp7T0PHdhWPNur7kAltbaJ44R0rAfkSz/KNc/h8CRe3dggS469CFOUYd4YolhSgfLAXdzO7nWXs3fNBeCjFJkbFiih7AvxjZ8XvlyMoE2QDSI4lBqk++P4LgMONsxEYaFYeQ1cM/p17XBVwrWfpDI1SLplyaje/cy0jjfjYcwftWaDNJrNzTj9qSmzfBG7Lu5u1HjMV+zLjd/HMxOreAj7ysaRhCT6dcLOgjUrEDL35JMKpLIxBJ3ebGxv4momeGOpGyDNe9gCYA0LdrTUJozwozRfdG13bvOqy1zDyCnxgmzxptCPVbCCNZ5apkU8ieiAJQOa7WNNbOS1yyc4mZy5rQ8KIExG7kSDMd7K2FMd50rwR+5cjmOpZnFTYmbu+GBW3lSYBuL0zo71XFjMu5HlsVHpvqqqFs1bEFaE55LOK21PDv3pMygS9xe66Rmhe8xslHIeL54OkIy5Z85kC9/MaWptCzVxQHEESHlFGcXYlqWSoPmNoxZqUqka7iRdmUyRmz8brE8LopUhAMCtqhZUJI7w2R1W/Epo4zA5HhoGAh+EroUx0pJ15MwcQJilnlIYCBNmeQJKID6ctDZsCawW3kWPixcpc4j7qsYRRj5HksMF4xkB9rXtAdK85ch7R6k8FTPtvHgEfp6l5TmD7U+d9j66B5twcLBDE7n1pXjwU8dbeeqLY1qUK5lj8EFoIZGt3PsYu63EFC9dVC0fOEyrQR5Wa+iuAcL12rzRtiNWgXtOqAuAO2gUv2GfZ1c64aw0zV
    github-token: AgABXZomTEAPY4yNnIjsm23S2G2dGG/dbtobYcDbHVDdFH2ERf5xFXO+8wXLtL0HsEhmVGHisZ/NzKjBzn0OmtgYeLy/MqSzNvluS9JyXJlg05Fd9r7yzu9PBpHDhq74ir9brYr01jkWP12Y9xeE53J5jVu6tiGxtsnZh5DwgdZgkzwwztpIwY4a1hRcgObZZDOUVO43AKYXThfkjkkcU+6hmTnxXOGYZ1b6QHzvWdtoCqD65GHmDJkOdUyJ5V0Eq/OoYavU/ALr7x7J7+KXio81gvMvyVHy7kiKATdY8STX+iWlVlpRkxkF+K0upBiqu117n6U7dQeSWa3GIEDDzC7dsP0uQ/EKuGu7zg6jW/m2LpxkXq0POsqhoyDXeVF92MepWexSrqHYjiwFPuaTCUwrovk2irgkH14HF/IOINBECB7DyOVuuRAwuw9RzxZlKXOmW9r6kOlMUt8Jj5GR2I2OW5ivwjqax8FqsYVOyzpQ37eRkDNolilDgBSxMY1v7wXRywynQbCYUmgQwJJGEneF8/fxiOBjmXwX/e1OPQn37Dc470QnjBemuXeKQgin/mDPCNOVzir7BqPSaD8qEC0/mlmlE0pg284Bj3XLOy67rPz4wyHol5/ouWNkdqF0X8s8CVQ67YdHa3VPSiMgchw/q9WkoPnD6dczx8w0gMBu3Uy5DH/3UxZ3qp7bBRjjGa/Null00oox4C8QyGNVuEov4i7pLXn51wtvgozFnADE2ShTE+Pw6KAN
  template:
    metadata:
      name: tokens-secrets
      namespace: gitops-app
    type: Opaque
