---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tokens-secrets
  namespace: gitops-app
spec:
  encryptedData:
    circleci-token: AgCxIKFat+IN615CP83S5Xmp9uftrYwnuI0ZFKUt3K+e5KbVTNO22tDNJ6Y//G7W3trdKHgHD6SjKq744kr9EX0IxmvkJjwUJdq13VF7bss5V/+hK7JlVWaDkuem651DAW57PzSYbXuqZr4uNlfnUOhZvt0eUvMT4xawdWU1K3dv4GJs31RXQUaU9KVfyOCn2MVsG91+9kdkCXag30x0YX1Al3fLnF/7ALBoxc5spIW0z4yy/HGyf2SPfbQpYd2ezaxgRUsqxl19KkbwhQQ9ZXJAvy3GUrXkhg4YgJ0vDIRAoWVOw8c1NcsuFWfzjOCxceEX3C4aiV5zMUHee7/8Jd37ewur4PuT/TX1Zv+AbzFRcSHUGNGwYeJHOCNLZSm+1jgt5E1/sm/ORCUMwg4n6GTc9xFHvI0c9rYu18bdI8K13HhCkOc7GsHkotP9EaKQJpCfl3WLXlalvwtUrmm+JNl/7zCYrqbeYx/jIfZVS4egmVPBsUM3784zVf+wtXC3nWqsUQ/IGFEBgSFiOapSsVBbiw+LB/oy8FaDGVFUx8Ev4yxCB5Mp0SrZoJkEG0edn8Af2oNKLAzUfwsyaM8IjfiQZLGy6FEsd/PJivXvpepcnIJ91NgFo4pxV34tarkzkMsT+G9Pabyl2InaHXkuULOyHPR+GTFgbt4F6ipsJp/cb1DinfZKcu9nkrz6oWJwq+pODn5It0pXrVcu9lg96fjP6lweDQMGhDKepEwBDnRqKOLVUdT5ZEPtVk+fZvaxvqAYVclul/98jyNeee7ac1TwC5FFckPl
    github-token: AgB4pQmNzcmQNNL6Pel8ySwiJn2CcaDBn0Oc5i54dz/+mlvmuqhq4/MNGOWGGocc38UIEZE7KxqxgBbt7b3kLOcrj9FasZ+52hpiIg9ss4xnbduKrIuqs0mv/+sPG5DZtm1hc/MIukE/dTqWByXEhtgqVSAswvSe3/LldYeI/OvY1OFyDFvrmDjg6BfBU+pcgHqeOQLxswmIwDOu75Isrqu40qL56aIIA7AHih8zaI8WAHSZovQu39agH1H0ADWoYua83YSr7DcJDPrAWFlqk62o7NqoMwyA9on+KYu/eodunDLUhlFDd38jtuTOskgyHyUxyDqBzAbBktQNaP+0XNci91PEIWwA9BOcgmdTEy43q18hlKB6w2pzgGa8WcprDpi515g6xSZUoIH+w1ZGme66A7wsakifZXjvJM3Hh5qPo87utFS3ZQKaibmRoWXxF4amGljIXuyghyzLqjIE4NPCO/flDnB+6FtE7hvfnQeBeMfvPag2ELkQGin/sK6WuRqKc70OKoUiym6ckvUASvviR30OzPGlNTrfJyo9kl+jSOYDZv4ZVSjrkxcH+GZbcqMBislX9lfmrDNQOnY4J8QVGxJBhNUM4amk5pmilLu2XJoZtggL5jce/ffs7wiQoPPZQ0ikJSI9nP7XGDD13SPnn/5oPz/Db4dP+lrbyQsVVGMdWbD8bFUPnj+blUJyphDTOPAep3ziuZRN2vpgftqmKcYCFp7Z6pcnPfk5W8F/OuudH3B09w9dÂº
  template:
    metadata:
      name: tokens-secrets
      namespace: gitops-app
    type: Opaque
