---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tokens-secrets
  namespace: gitops-app
spec:
  encryptedData:
    circleci-token: AgCXRpPvBqpPOPi5xlhPjlfflYuss/5Fx9BHr893iRBPevU779IHRwjaHGhDQdRolbORwKo+JZNENmomUmaMxpR7rtWJ4nzPSCosaWT66kRED3uV8lhDUzTJNxzOuk+PjgAW4gWnmObTOvrlc4WO4/TCliZEY4J7j153UTX/R9mxkoC9vSekcj2UbqmZ/Uw5EGr/vKJEg26aKR9DDyrWO1Y0qUUXYq6AeLcSCOTGjZ8PQZEsAFgifzBYuSKbBkxQ5VcNwDiE6JNxKZEfmQSkGPMN0E+9Mjzhr1mTChltpe3Cg9hkbdL4yRxxSnD0VqNXs0jvsUAcwPbpOIjlDXRItCn29iqLqjyMlf/+130oBR99OemYMDbRbOSXuUQAVXmzkf+841woODrUL7LBYNzshqjFo6KIllYH804xW4NgLc/pi8ZMbn0kSTJfkHOxc6Hpb8ER81WCYlkB1paQ9wam3qoVAJth8meDJPXGyV3ssdqsC9gviv3uUzrIPCQClVUxD4sB1fA15XcgfZg9tBTf+RGMYv7qjPl/01s2iEaHqiZeTtRokOO4EC9o7YeTp/ntzSrrON19zH0WLbfxAJ5ZDi8dqMX0v54NKKTCmPZj7PsNgvFvn77UUTF0Iz1H2EqTDYlf0bbBPR3XLawWC3bRupz1wBLJ7ycOCJKURUnFcUHeRRrb6Mv24RLXxz4gnPRjk728XwKV42xFTXifY0fYPuJvk4GcG58al4Eu/SOmwmiKp6yGfk3D/CaBDAGb9+kAJQ0YDZRgwd6GQcJy16hZFYXm2D6anQKY
    github-token: AgB1Oham0+h9Ovsl5XtnKKh+o/dzmx5tf7Dlz2e+s5Uxw7+oT4PWGSgEtd4x/KFQIHMDOgw4FQbtjuS55ZVizomcliZcab5ofvRl5WyAdE6PwZdfct6gQTAGR8pKJzCbtbSuM64ZDCdHC/ICysVVZN4tQcuCWZHfNQtL/tSYgtXV3JbDnYPkV+rZhweNh4yJMzGVaJusLys3Le+0OkMfLn7w0WcvHDlNyrE0/PPnPJM7WvIfEsbA+L0TkaZiHQUpL4+ziwVaHtNdiEgOC6XLdYORETvTrDr5KAuVk8F6jQUNI9UvBvt8ZKCS9u2zWDVmwrgTUkUMyJouUCQfmlusWoaLRzGgwaFaherhgkaKcoZ3L/u+qApGfPr7Q2UwsOaa939JWR6zdjwU4EZuSULEw3X51PLzpCix71ttauYGYU/1Mcw0BgrjXEPWSN+Kh7Y22BykDkD3JBJyyu72HDIMizxbAB9QONB5IRgQcTeQOSj5MSn880t3V97dVo3HzJNtDbU2k2PjCmVZB8Niq5hpAbK0oaQdO37b9jO2xtwuFLX4RTJcGbnYxrUhGhr2gPR2XOKMixQHFZ154NDe1CbK3dqZLt9PURoVVIR+N7DPC414o50Z3f3nbUIDNylvPuUxpCeWUFFXd2rGs5buB1T0Sa3k32atqVlhz99g6pJUvRhraDij0KZpNBUrzDIYkvMh7xObRYhll2ULWn0uKXDxFnnUxbFiEEg0kw43rYHPfQG0OPFLuQJ3HFNQ
  template:
    metadata:
      name: tokens-secrets
      namespace: gitops-app
    type: Opaque
