---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tokens-secrets
  namespace: gitops-app
spec:
  encryptedData:
    circleci-token: AgALLK8O5DHdPI140romOBNhiFfL7mENwikLTGI/0SIEoqF2ELjR+vfluK49AV+kI5V+Ee1r41/n6vbZHghu9maAJscGKaCB5sh5vGkRShxV9J5bNAUvPV95zGk7aByVwnz0CYf5atEI8UnDBED03juC/Skk52gOdGjJFqoUcwA2VMBNDS63Gd2FeW9k1TdZm2c1l6P7F4daY97T25ftVsOckHCJthT5Z2GALUUC8wa57abiMfTx0u1pS6WaXGp5bQMQbQ3LudwF3C4XqllMNZ0HnP9FlOnfOdpufWpGlSODcz1gLd+hb4l9Fjwim/EUkqCS16cXPSvllJKOYau8NSg6PfqCzyvfOOHeIaG1FTFzpJpXDmn7LUFiFdsn+fMA6uxKvAbqE4De1Ij6y4q7vMi9A0es/nNaF5zMCZ4keFhDmH3xLsWL8oYrd0/yahtaJ6DXrvwG1atHoTLTlqq5+W6axozJgh0OZhpRycofvqgETfMtrKRe8aVbcCmuLtO1nAlXUWfzHTH1Jsjo+TSgmdCrhfJZZbeJt+QKaeCuc73OUubsmS2+eVQtgz/ixOsNMXliRWLWXWEahm9sf2cd+hHIxAgip5iUqwSHIpm9IPghOoxJG+4KwWnFEtCJ7S1g7nJbgS61YLr5xRM3Vzvu4qdST3R3hs30jtr8gPRrTRP4QcdXijZ2/NkJH4D3lL3AOTuUXkTBAKFA2P3WYWmB3SeA30/SfMWhJmQHOSZmB5XtsOnaJTXPsFxMiJ+8MiaXx8u89IN492nWOb2bMadIP8WJTsQ/5zda
    github-token: AgCKw71Z33WlLHGClkV+QWSFyB2PJyMFiAeDWL9IvZrNQ4+Hv8R8P+O9DIqJs3v6i8Phr/EGSXa+wLUgEcDloMkZzepJEkt/EnmPZxUlEzmllTWuIzx8eUT3vfpjX1VXBAM2DnSNjZqhRNGBYNVyB4U3yHlfSTcGuRLWPgwfxX7Cl05rJCMMzQbiQ1fsMWnMkUWRi1+TDh/dj4f/EwSB7tozvxebQosrZDhy2Bg45IeHN6P7+f7PC/2edspNZfgF1CU4Oc920hVETYqFusoOH+ELH8l3Fr1h0bhScDlKwnP/PxIX6k0ZMG4erWK0KcgCEM9NS+6lkHnOqOvYN3l9aYNJEWfsYl/b/Jj9nTTQ/XZBk++vJTbPg3ni68huq3InLytuKdximoUro+Q2chuqb0so5T2nXFKRf6AdjIx/+FYrtrIjcj8X1BCNPeGSjC/fYKG72uq0qwLY/q93YW9fNJwk0xQcB1s3/0lUiDXjYXW1RgSWARDbfJms2iqY3u7tslIdwu5wh6XFYRWqEjEYYWhnc3IGvBSzujj6txXSNvKi+ttuYNKzZn9D5GNc9P5nzzJdD4EmUUv0hAtdVT/ImxidbgdSD+hGonQtJQLfVD90jAWwcib0RIyAW/AIbL88KuF890WzHOqS7Fh3cVCKlLSql8r4jjijN/M0lo9+YfmRZjIBIDIgfoMu8HGrImnwa/PYw0NH++CaJzwWOVum9JnMTGiafxcxx2IMp9LUxCzOQ3RIUd2VbJ7e
  template:
    metadata:
      name: tokens-secrets
      namespace: gitops-app
    type: Opaque
