---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tokens-secrets
  namespace: gitops-app
spec:
  encryptedData:
    circleci-token: AgCBdzah4SKrru/P+xMwMcOPcKoWCDqamJCdOqWat1Ww2jDYPJB/M+PGjXEiempAphInS4vV9pG65MphjoYbn93dL0yQMdyFHbnG0ppkhxqKjNZKG4oDuZtkS1CXLBIbbj8RI2ao7n84qjOJHZAetyvRYsaghugEMQ50WDp2nBSyL+/mnJjyBRrf9+F5sCrn0FYUlQKlbZ2o9RUVGinrQrCZsjLF82BZBybE7zsi92xEp9Qvwx2wZAFeqkAtsVaPns/Svu0M+O5eP9SOMRWW+kURDDMevDnlvc/YiX4Zk+iVkNIAxsURw3N4Ryl8eCoIEAySle04QQxfOLTCnOcDQrrLkT7fcDyT8uIvgdI96Oz2oV2HuVWhSyLL3EfIlgzfsBqB3/R55zbUrJzQOuhqLNuIGGLiOo+keQ5R34+M/s2ED2AEmmwq8CF+IOEMw1w1UAzz7WkJAKuKyjfbXEhhPh1o5j5RCdtXRuKDN6fizIslLEF1x2hj9RJCC8rMeJjftBMar5MRRIQY/08tMKpIlnLLdq39xkmcRIn3UDczENEIEF8RtRqHOrr6b1FyOatpe5YoghSyb7w96Atbq+hLn5AxEKIuSNBFEYt70CKrCN3o5v2LXBsHqu/E1zfHTSWFvIR2Xfa8U9MSBQpS0/ShT4clB/6IQH0HYjmiSyPL308mZso00slQ5sNg7dzPDjxQo9cZB4l8UjgjkjefiJbNXlH4SjtShXEBJLbTwCEZKLolrAilTMVZCfVN/jC5usr0x9vPYm4Xl/8wtiQVOdIx9KFgfu9q6Adk
    github-token: AgCw3UzkoTQXB166x0ybF6QYQ34rjptRu6Wbqe7l1rbca+W57hgePRy678kUfj5bHUw971+4/dnrKGWNHR3yUAUW6udqbEjPjqxFrJfW6gS9LRLFp+QVle4qdDJptqKwwI+knWgS825ouaPAGPxDAuOlhPcw3qfe7uoDVqWdGN6PtdUhLee/jDCc/2060Jil/AGOnA9UdN9VGFEwpdXly7RWGHLpmCo6ZD2w+445cScJJHFT+8AC2pkDLotZvjTT+tA8SwHXQVcW9lOWfdT5/P45SGNIyI3qv6S6Bnx3jbJDMG9AdghHKWMr/xHltdEFZOqwiymY2HRLxBYckeVTJ7R/TP0+HxbAyLkb4/RL/VW3sH6xINzIqF1R44CQEtkNwCgLTGqByUwbUmueLRdrh5lM3iS/pRYJQzl+0y6qAU1SWjfHnRai8BBAEvOfZiV9P/Wr62NCuxHJDFCCV92SH8zmL8I8I3V6IOwFOvfYbPG7jQ7XQLkueS9P7tpAtSTidPKKfrawJJqDOCT8txhldf1xfMtf+4fHTPbGN/zJ3Q1puHkLHF4sq7EvE+bDG9kO2T0wbPHZB53dDKQ7a77kLHKk0Z2/BI6EG+aJN8f7n3kDXHvoM3dcEmslBHIs0HghfaHGecBfZbmPA20nLt1NjpKUCGxsJ/4RNwaNonkXJsRyqsNSS1ma1WuCuxnLDTL7oEzbgPgpqK75WukLi/Gg/+ibgk488lYbNespK5BOqvsDE2kDXFcMMNDC
  template:
    metadata:
      name: tokens-secrets
      namespace: gitops-app
    type: Opaque
